services:

  parking-db:
    platform: linux/x86_64
    image: mysql:8.0.33
    restart: always
    container_name: parking-db
    networks:
      - services
    ports:
      - 3306:3306
    volumes:
      - parking-db-volume:/var/lib/mysql
      - ./.docker/sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=parking
      - MYSQL_DATABASE=parking
      - MYSQL_PASSWORD=parking
      - MYSQL_ROOT_PASSWORD=parking
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0

  parking-hexagonal-java-dev:
    container_name: parking-hexagonal-java-dev
    image: pablords/parking-hexagonal-java-dev:latest
    build:
      context: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005

  parking-hexagonal-java:
    container_name: parking-hexagonal-java
    image: pablords/parking-hexagonal-java:latest
    depends_on:
      - parking-db
    build: 
      args:
        JAR_FILE: target/parking-0.0.1-SNAPSHOT.jar
    networks:
      - services
    volumes:
      - ./src/main/resources/application.yml:/app/config/application.yml
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8080:8080
    command: java -jar /app.jar --spring.config.location=file:/app/config/application.yml
    # command: sleep infinity

volumes:
  parking-db-volume:


networks:
  services:
    driver: 'bridge'
