# Configuração do datasource
spring:
  datasource:
    url: jdbc:mysql://parking-db:3306/parking
    username: parking
    password: parking

# Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

# Ativação do perfil de produção
  config:
    activate:
      on-profile: prod
