spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # ⚠️ Evita a criação automática das tabelas

config:
  activate:
    on-profile: contract-test

logging:
  level:
    root: OFF  # Desliga todos os logs
    # org.springframework: ERROR  # Mostra apenas erros críticos do Spring
    # com.pablords: ERROR  # Mostra apenas erros críticos do seu código