



spring:
  datasource:
    url: jdbc:mysql://parking-db:3306/parking
    username: parking
    password: parking
    initialization-mode: never
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # ⚠️ Evita a criação automática das tabelas

config:
  activate:
    on-profile: test