name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configura a versão do Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache do Maven
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Obtém a versão do projeto
      - name: Get Project Version
        id: project-version
        run: echo "::set-output name=VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      # Build da aplicação
      - name: Build Application
        run: mvn clean package

      # Executa os testes
      - name: Run Tests
        run: mvn test

    outputs:
      VERSION: ${{ steps.project-version.outputs.VERSION }}

  package:
    name: Package Application as Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Debug para verificar a versão
      - name: Debug Version
        run: echo "VERSION=${{ needs.build.outputs.VERSION }}"

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build \
            -t pablords/parking:${{ needs.build.outputs.VERSION }} \
            --build-arg JAR_FILE=target/parking-${{ needs.build.outputs.VERSION }}.jar .

      # Push da imagem Docker para o registry
      - name: Push Docker Image
        run: |
          docker push pablords/parking:${{ needs.build.outputs.VERSION }}

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: package

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy da aplicação
      - name: Deploy Application
        run: |
          echo "Deploy steps go here..."
          # Adicione os comandos para realizar o deploy, como kubectl ou comandos de infraestrutura
